# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/blogdb
spring.datasource.username=bloguser
spring.datasource.password=StrongPassword123!
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# # Database connection (with defaults for local dev)
# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/blogdb}
# spring.datasource.username=${SPRING_DATASOURCE_USERNAME:bloguser}
# spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:StrongPassword123!}
# spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA settings
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Database Connection Pool
spring.datasource.hikari.maximum-pool-size=200
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
# spring.datasource.hikari.leak-detection-threshold=60000

# JPA/Hibernate Settings
spring.jpa.properties.hibernate.connection.provider_disables_autocommit=true
spring.jpa.properties.hibernate.connection.autocommit=false
spring.datasource.hikari.auto-commit=false


# Enable SQL logging to debug
# spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Transaction timeout
spring.transaction.default-timeout=30

#Jwt 
jwt.secret=mySuperSecretKeyThatIsAtLeast256BitsLongAndSecure123456789
