server:
  port: 8080   

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oneblog?useSSL=false&serverTimezone=UTC
    username: oneblog
    password: oneblog

  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true        
    properties:
      hibernate:
        format_sql: true  