
spring.datasource.url=jdbc:mysql://localhost:3306/01blog
spring.datasource.username=oneblog
spring.datasource.password=oneblog
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect